DELETE http://localhost:3000/changelogs/68ed09d8c7501de21c112f19 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk5MGYxZGVhYmRiNDNjMjEzNWFjMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDM2NDEyNiwiZXhwIjoxNzYwOTY4OTI2fQ.xmCmChnN_QulcdSGB7L_NetW11ION4XJHgDH4E6RaxM
