POST http://localhost:3000/changelogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk5MGYxZGVhYmRiNDNjMjEzNWFjMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDI2MjY1NCwiZXhwIjoxNzYwODY3NDU0fQ.pimURWYs_mQiNIeHHFvpWWZiVRVJoEshzFrsIBbsCsA

{
    "title": "NEW `Changelog` FUNCTIONALITY ADDED",
    "version": "1.2.1",
    "description": "Added a new `Changelog` functionality to keep users informed about the latest updates and improvements. This feature enhances transparency and helps users stay up-to-date with the application's development.",
    "date": "2025-10-14"
}